version: "3.9"
services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_restaurant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_restaurant_app
    restart: always
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: social_restaurant
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  db_data:
